import 'package:flutter/material.dart';

/// ! DO NOT EDIT THIS FILE MANUALLY
/// This file was generated from the Stitch Project: Family Budget Planner
/// Last extracted: 2026-04-19

class DesignTokens {
  const DesignTokens._();

  // ── Colors: Light Mode (The Empathetic Ledger) ──────────────────
  static const Color lightPrimary = Color(0xFF005BBF);
  static const Color lightOnPrimary = Color(0xFFFFFFFF);
  static const Color lightPrimaryContainer = Color(0xFF1A73E8);
  static const Color lightOnPrimaryContainer = Color(0xFFFFFFFF);

  static const Color lightSecondary = Color(0xFF006E2C);
  static const Color lightOnSecondary = Color(0xFFFFFFFF);
  static const Color lightSecondaryContainer = Color(0xFF86F898);
  static const Color lightOnSecondaryContainer = Color(0xFF00722F);

  static const Color lightTertiary = Color(0xFF795900);
  static const Color lightOnTertiary = Color(0xFFFFFFFF);
  static const Color lightTertiaryContainer = Color(0xFF987000);
  static const Color lightOnTertiaryContainer = Color(0xFFFFFFFF);

  static const Color lightError = Color(0xFFBA1A1A);
  static const Color lightOnError = Color(0xFFFFFFFF);
  static const Color lightErrorContainer = Color(0xFFFFDAD6);
  static const Color lightOnErrorContainer = Color(0xFF93000A);

  static const Color lightBackground = Color(0xFFF7F9FF);
  static const Color lightOnBackground = Color(0xFF181C20);

  static const Color lightSurface = Color(0xFFF7F9FF);
  static const Color lightOnSurface = Color(0xFF181C20);
  static const Color lightSurfaceVariant = Color(0xFFE0E2EC);
  static const Color lightOnSurfaceVariant = Color(0xFF44474F);

  static const Color lightSurfaceContainerLowest = Color(0xFFFFFFFF);
  static const Color lightSurfaceContainerLow = Color(0xFFF1F3FA);
  static const Color lightSurfaceContainer = Color(0xFFEBEDF5);
  static const Color lightSurfaceContainerHigh = Color(0xFFE5E7EF);
  static const Color lightSurfaceContainerHighest = Color(0xFFDFE3E8);

  static const Color lightOutline = Color(0xFF74777F);
  static const Color lightOutlineVariant = Color(0xFFC1C6D6);

  // ── Colors: Dark Mode ──────────────────────────────────────────
  static const Color darkPrimary = Color(0xFF9ACBFF);
  static const Color darkOnPrimary = Color(0xFF003258);
  static const Color darkPrimaryContainer = Color(0xFF004B82);
  static const Color darkOnPrimaryContainer = Color(0xFFCEE4FF);

  static const Color darkSecondary = Color(0xFF66DD8B);
  static const Color darkOnSecondary = Color(0xFF003917);
  static const Color darkSecondaryContainer = Color(0xFF005425);
  static const Color darkOnSecondaryContainer = Color(0xFFADF5C3);

  static const Color darkTertiary = Color(0xFFF3C043);
  static const Color darkOnTertiary = Color(0xFF3E2E00);
  static const Color darkTertiaryContainer = Color(0xFF5B4400);
  static const Color darkOnTertiaryContainer = Color(0xFFFFDF9C);

  static const Color darkError = Color(0xFFFFB4AB);
  static const Color darkOnError = Color(0xFF690005);
  static const Color darkErrorContainer = Color(0xFF93000A);
  static const Color darkOnErrorContainer = Color(0xFFFFDAD6);

  static const Color darkBackground = Color(0xFF111318);
  static const Color darkOnBackground = Color(0xFFE2E2E9);

  static const Color darkSurface = Color(0xFF111318);
  static const Color darkOnSurface = Color(0xFFE2E2E9);
  static const Color darkSurfaceVariant = Color(0xFF44474F);
  static const Color darkOnSurfaceVariant = Color(0xFFC4C6CF);

  static const Color darkSurfaceContainerLowest = Color(0xFF0C0E13);
  static const Color darkSurfaceContainerLow = Color(0xFF191B21);
  static const Color darkSurfaceContainer = Color(0xFF1D1F26);
  static const Color darkSurfaceContainerHigh = Color(0xFF282A31);
  static const Color darkSurfaceContainerHighest = Color(0xFF33353C);

  static const Color darkOutline = Color(0xFF8D9099);
  static const Color darkOutlineVariant = Color(0xFF44474F);

  // ── Typography Scale: Display & Headlines (Manrope) ────────────
  static const String displayFontFamily = 'Manrope';
  static const double fontSizeDisplayLarge = 44.0; // 2.75rem
  static const double fontSizeDisplayMedium = 36.0; // 2.25rem
  static const double fontSizeDisplaySmall = 28.0; // 1.75rem
  static const double fontSizeHeadlineLarge = 32.0; // 2rem
  static const double fontSizeHeadlineMedium = 28.0; // 1.75rem
  static const double fontSizeHeadlineSmall = 24.0; // 1.5rem

  // ── Typography Scale: Body & Labels (Inter) ─────────────────────
  static const String bodyFontFamily = 'Inter';

  static const double fontSizeTitleLarge = 20.0; // 1.25rem
  static const double fontSizeTitleMedium = 18.0; // 1.125rem
  static const double fontSizeTitleSmall = 16.0; // 1.0rem
  static const double fontSizeBodyLarge = 16.0; // 1.0rem
  static const double fontSizeBodyMedium = 14.0; // 0.875rem
  static const double fontSizeBodySmall = 12.0; // 0.75rem
  static const double fontSizeLabelLarge = 14.0; // 0.875rem
  static const double fontSizeLabelMedium = 12.0; // 0.75rem
  static const double fontSizeLabelSmall = 11.0; // 0.6875rem

  // ── Spacing Scale ──────────────────────────────────────────────
  static const double spacingXXS = 2.0;
  static const double spacingXS = 4.0;
  static const double spacingSM = 8.0;
  static const double spacingMD = 16.0;
  static const double spacingLG = 24.0;
  static const double spacingXL = 40.0;
  static const double spacingXXL = 64.0;

  // ── Shape / Corner Radius ──────────────────────────────────────
  static const double radiusXS = 4.0;
  static const double radiusSM = 8.0;
  static const double radiusMD = 12.0;
  static const double radiusLG = 16.0;
  static const double radiusXL = 24.0;
  static const double radiusFull = 9999.0;

  // ── Elevation & Gradients (Custom Tokens) ───────────────────────
  static const double ambientShadowBlur = 24.0;
  static const double ambientShadowOpacity = 0.06;
  static const Offset ambientShadowOffset = Offset(0, 8);

  static const List<Color> lightPrimaryGradient = [
    lightPrimary,
    lightPrimaryContainer,
  ];

  static const List<Color> darkPrimaryGradient = [
    darkPrimary,
    darkPrimaryContainer,
  ];

  static const List<Color> progressGradient = [
    Color(0xFF66DD8B), // Secondary (Emerald)
    Color(0xFF9ACBFF), // Primary (Soft Sky)
  ];
}
